# Copyright Takeshi Yonezu. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  node:
    image: hyperledger/${IROHA_IMG}
    ports:
      - "50051:50051"
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 5;
      su - iroha -c /opt/iroha/config/run-iroha.sh"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
