# Copyright Takeshi Yonezu. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:

  node1:
    image: hyperledger/${IROHA_IMG}
    ports:
      - "50051:50051"
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store1:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 5;
      /opt/iroha/bin/irohad --config config/iroha1.conf
      --genesis_block config/genesis.block
      --keypair_name config/node1"
    depends_on:
      - postgres1

  node2:
    image: hyperledger/${IROHA_IMG}
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store2:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 5;
      /opt/iroha/bin/irohad --config config/iroha2.conf
      --genesis_block config/genesis.block
      --keypair_name config/node2"
    depends_on:
      - postgres2

  node3:
    image: hyperledger/${IROHA_IMG}
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store3:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 5;
      /opt/iroha/bin/irohad --config config/iroha3.conf
      --genesis_block config/genesis.block
      --keypair_name config/node3"
    depends_on:
      - postgres3

  node4:
    image: hyperledger/${IROHA_IMG}
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store4:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 5;
      /opt/iroha/bin/irohad --config config/iroha4.conf
      --genesis_block config/genesis.block
      --keypair_name config/node4"
    depends_on:
      - postgres4

  node5:
    image: hyperledger/${IROHA_IMG}
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store5:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 5;
      /opt/iroha/bin/irohad --config config/iroha5.conf
      --genesis_block config/genesis.block
      --keypair_name config/node5"
    depends_on:
      - postgres5

  node6:
    image: hyperledger/${IROHA_IMG}
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store6:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 5;
      /opt/iroha/bin/irohad --config config/iroha6.conf
      --genesis_block config/genesis.block
      --keypair_name config/node6"
    depends_on:
      - postgres6

  node7:
    image: hyperledger/${IROHA_IMG}
    environment:
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - .:/opt/iroha/config
      - ./block_store7:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    command: >
      bash -c "sleep 5;
      /opt/iroha/bin/irohad --config config/iroha7.conf
      --genesis_block config/genesis.block
      --keypair_name config/node7"
    depends_on:
      - postgres7

  postgres1:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres2:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres3:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres4:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres5:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres6:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres7:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
